var configJson = {
    "protein":{
        "glycosylation":{
        }   
        ,"disease":{
        },
        "publication":{
        },
        "orthologs":{
        },
        "snv":{
        }
        ,"crossref":{
        },
        "site_annotation":{
        },
        "function":{
        },
        "pathway":{
        },
        "refseq":{
        },
        "mass":{
        }
        ,"uniprot":{
        }
        ,"protein_names":{
        }
        ,"gene_names":{
        }
        ,"species":{
        }
        ,"isoforms":{
        }
        ,"gene":{
        }
        ,"go_annotation":{
        }
        ,"expression_disease":{
        }
        ,"expression_tissue":{
        }
        ,"synthesized_glycans":{
        }
        ,"interactions":{
        }
    },
    "glycan":{
        "mass":{
        }
        ,"mass_pme":{
        }
        ,"iupac":{
        }
        ,"glycam":{
        }
        ,"glycoct":{
        }
        ,"inchi":{
        }
        ,"wurcs":{
        }
        ,"smiles_isomeric":{
        } 
        ,"inchi_key":{
        }
        ,"species":{
        }
        ,"glycoprotein":{
        }
        ,"enzyme":{
        }
        ,"residues":{
        }
        ,"motifs":{
        } 
        ,"classification":{
        }
        ,"composition":{
        }
        ,"crossref":{
        }
        ,"publication":{
        }
    }
};

